apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${{ values.component_id }}
  name: ${{ values.component_id }}
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ${{ values.component_id }}
  type: ClusterIP
