apiVersion: apps/v1
kind: Route
metadata:
  labels:
    app: ${{ values.component_id }}
  name: ${{ values.component_id }}
spec:
  spec:
    port:
      targetPort: 8080-tcp
    subdomain: ${{ values.component_id }}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${{ values.component_id }}
      weight: 100
